version: "3.7"

networks:
  t2-net:
    driver: bridge

secrets:
  t2.superadmin.list:
    external: false
    file: ./_dev-secrets/t2.superadmin.list.dev
  t2.admin.list:
    external: false
    file: ./_dev-secrets/t2.admin.list.dev
  t2.admin.password:
    external: false
    file: ./_dev-secrets/t2.admin.password.dev
  t2.classic.superadmin.password:
    external: false
    file: ./_dev-secrets/t2.classic.superadmin.password.dev
  t2.classic.telnet.password:
    external: false
    file: ./_dev-secrets/t2.classic.telnet.password.dev
  t2.classic.telnet.listen.password:
    external: false
    file: ./_dev-secrets/t2.classic.telnet.listen.password.dev