version: "3.7"

services:

  t2:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # TODO
      T2_SERVERNAME: "T2DockerTest"

    secrets:
      - source: t2.superadmin.list.v1
        target: t2.superadmin.list
      - source: t2.admin.list.v1
        target: t2.admin.list
      - source: t2.admin.password.v1
        target: t2.admin.password
      - source: t2.classic.superadmin.password.v1
        target: t2.classic.superadmin.password
      - source: t2.classic.telnet.password.v1
        target: t2.classic.telnet.password
      - source: t2.classic.telnet.listen.password.v1
        target: t2.classic.telnet.listen.password

    ports:
      - target: 28000
        published: 28000
        protocol: udp
        mode: host
      - target: 666
        protocol: tcp
        published: 27999
        mode: host
                   
    networks:
      - t2-net

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

    logging:
      options:
        max-size: "10m"

networks:
  t2-net:
    driver: overlay

secrets:
  t2.superadmin.list:
    external: true
    name: t2.superadmin.list.v1
  t2.admin.list:
    external: true
    name: t2.admin.list.v1
  t2.classic.superadmin.password:
    external: true
    name: t2.classic.superadmin.password.v1
  t2.classic.telnet.password:
    external: true
    name: t2.classic.telnet.password.v1
  t2.classic.telnet.listen.password:
    external: true
    name: t2.classic.telnet.listen.password.v1    