version: "3.7"

services:

  t2:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      T2_SERVERNAME: "Testing Grounds"
      T2_MAX_PLAYERS: 64
      T2_DEFAULT_MISSIONTYPE: "CTF"
      T2_DEFAULT_MAP: "HighOctane"
      T2_AUTOPW_ENABLED: 1
      T2_PUGAUTOPW_ENABLED: 1
      T2_PUGPW_ALWAYSON: 1
      T2_SERVER_PASS: "pickup"
      T2_MOTD: "<color:3cb4b4><font:Sui Generis:22>Welcome\\n<color:3cb4b4><font:Univers:16>Get Mappacks at https://playt2.tk"
      T2_LoadScreenMOTD1: "Have fun!"
      T2_LoadScreenMOTD2: " "
      T2_LoadScreenMOTD3: " "
      T2_ADMIN_LIST: ""
      T2_SA_LIST: "4230323\\t4095669"
    secrets:
      - t2.admin.password
      - t2.classic.superadmin.password
      - t2.classic.telnet.password
      - t2.classic.telnet.listen.password

    ports:
      - target: 28000
        published: 28000
        protocol: udp
        mode: host
      - target: 666
        protocol: tcp
        published: 27999
        mode: host
                   
    networks:
      - t2-net

    healthcheck:
      test: ["CMD-SHELL", "nc -z -u 127.0.0.1 28000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

    logging:
      options:
        max-size: "10m"

networks:
  t2-net:
    driver: overlay

secrets:
  t2.admin.password:
    external: true
    name: t2.admin.password.v1    
  t2.classic.superadmin.password:
    external: true
    name: t2.classic.superadmin.password.v1
  t2.classic.telnet.password:
    external: true
    name: t2.classic.telnet.password.v1
  t2.classic.telnet.listen.password:
    external: true
    name: t2.classic.telnet.listen.password.v1    